version: "3.9"

volumes:
  mysql-store:
services:
  app:
    container_name: php_template_app
    image: template/php8-fpm:1.0
    build:
      context: .devcontainer/
      dockerfile: ./app/Dockerfile
      args:
        - UID=$UID
        - GID=$GID
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    working_dir: '/var/www'
    volumes:
      - .devcontainer/app/php.ini:/usr/local/etc/php/php.ini
      - .devcontainer/app/xdebug.ini:/usr/local/etc/php/xdebug.ini
      - ./src:/var/www
    depends_on: 
      - db
  phpdoc:
    container_name: php_template_phpdoc
    image: template/phpdoc:1.0
    build:
      context: .devcontainer/
      dockerfile: ./phpdocumentor/Dockerfile
    volumes:
      - ./src:/data

  web:
    container_name: php_template_nginx
    image: template/nginx:1.0
    build:
      context: .devcontainer/
      dockerfile: ./nginx/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - .devcontainer/nginx/conf.d/:/etc/nginx/conf.d/
      - ./src:/var/www
  db:
    container_name: php_template_db
    image: template/mysql:1.0
    build:
      context: .devcontainer
      dockerfile: ./mysql/Dockerfile
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=develop
      - MYSQL_USER=develop
      - MYSQL_PASSWORD=develop
      - TZ=Asia/Tokyo
    volumes:
      - type: volume
        source: mysql-store
        target: /var/lib/mysql
        volume:
          nocopy: true
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: 'db'
    ports:
    - 8081:80