version: "3.9"

volumes:
  php-fpm-socket:
  mysql-store:
services:
  app:
    container_name: php_template_app
    image: template/php8-fpm:1.0
    build:
      context: ./
      dockerfile: ./app/Dockerfile
      args:
        - UID=$UID
        - GID=$GID
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    working_dir: '/var/www'
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./app/php.ini:/usr/local/etc/php/php.ini
      - ./app/xdebug.ini:/usr/local/etc/php/xdebug.ini
      - ../src:/var/www
    depends_on: 
      - db
  phpdoc:
    container_name: php_template_phpdoc
    image: template/phpdoc:1.0
    build:
      context: ./
      dockerfile: ./phpdocumentor/Dockerfile
    volumes:
      - ../src:/data
  web:
    container_name: php_template_nginx
    image: template/nginx:1.0
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ../src:/var/www
  db:
    container_name: php_template_db
    image: template/mysql:1.0
    build:
      context: ./
      dockerfile: ./mysql/Dockerfile
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=develop
      - MYSQL_USER=develop
      - MYSQL_PASSWORD=develop
      - TZ=Asia/Tokyo
    volumes:
      - type: volume
        source: mysql-store
        target: /var/lib/mysql
        volume:
          nocopy: true